import { fakerIT, Faker } from "@faker-js/faker"

export const getEmptyObjectArray = (length: number) => {
  return Array.from({ length }, () => ({}))
}

export type InsertDataPayload<T, U> = {
  partial: Partial<T>
  idx: number
  additionalProperties: U
  faker: Faker
}

export const stringToNumber = (str: string) => {
  return str.split("").reduce((acc, char) => acc + char.charCodeAt(0), 0)
}

export type InsertDataFn<T, U> = (options: InsertDataPayload<T, U>) => T

export const genericCreateInsertData = <T, U = null>(options: {
  getInsertDataEntity: InsertDataFn<T, U>
  autoGeneratedDefaultLength?: number
}) => {
  let idx = 0
  const { autoGeneratedDefaultLength = 10, getInsertDataEntity } = options

  return (innerOptions: {
    autoGeneratedLength?: number
    additionalPartials?: Partial<T>[]
    additionalProperties: U
    faker?: Faker
  }): T[] => {
    const {
      autoGeneratedLength = autoGeneratedDefaultLength,
      additionalPartials = [],
      additionalProperties,
      faker,
    } = innerOptions || {}

    return additionalPartials
      .concat(getEmptyObjectArray(autoGeneratedLength))
      .map((e) =>
        getInsertDataEntity({
          partial: e,
          idx: idx++,
          additionalProperties,
          faker: faker ?? fakerIT,
        }),
      )
  }
}

export const useValueOrDefault = <V, D>(
  value: V,
  defaultValue: D,
  chance: number = 0.5,
): V | D => {
  chance = Math.min(Math.max(chance, 0), 1)
  const useFakerValue = Math.random() < chance

  if (useFakerValue) {
    return value
  } else {
    return defaultValue
  }
}

export const generateFakeJson = (faker: Faker, param: number) => {
  const fakeData: { [key: string]: string } = {}
  for (let i = 0; i < param; i++) {
    fakeData[faker.lorem.word()] = faker.lorem.word()
  }
  return fakeData
}
