/*
  * This file was generated by scripts/assets_types.ts
  * Do not edit this file manually
  */

import { User } from "$services/UsersService"

export type GlobalResourcesFavicon = {
  "android-chrome-192x192.png": string
  "android-chrome-512x512.png": string
  "apple-touch-icon.png": string
  "favicon-16x16.png": string
  "favicon-32x32.png": string
  "favicon-96x96.png": string
  "favicon.ico": string
  "site.webmanifest": string
}

export type GlobalResourcesFonts = {
  "Roboto-Bold.ttf": string
  "Roboto-BoldItalic.ttf": string
  "Roboto-Italic.ttf": string
  "Roboto-Light.ttf": string
  "Roboto-LightItalic.ttf": string
  "Roboto-Medium.ttf": string
  "Roboto-MediumItalic.ttf": string
  "Roboto-Regular.ttf": string
  "Roboto-SemiBold.ttf": string
  "Roboto-SemiBoldItalic.ttf": string
}

export type GlobalResourcesImages = {
  "authBg": string
  "challengesEmpty": string
  "grid": string
  "heroBg": string
  "homeHeroBg": string
  "homeHero": string
  "homeOverview": string
  "resultsEmpty": string
}

export type GlobalResourcesScripts = {
  main: string
}

export type GlobalResourcesStyles = string[]

export type GlobalResourcesRecaptcha = {
  RECAPTCHA_ACTIVE: boolean
  V2_SITE_KEY: string
  V3_SITE_KEY: string
}

export type GlobalResourcesSentry = {
  SENTRY_DSN: string | null
  ENVIRONMENT: string
  SENTRY_VERSION: string | null
}

export type GlobalResources = {
  FAVICON: GlobalResourcesFavicon
  FONTS: GlobalResourcesFonts
  IMAGES: GlobalResourcesImages
  SCRIPTS: GlobalResourcesScripts
  STYLES: GlobalResourcesStyles
  RECAPTCHA: GlobalResourcesRecaptcha
  SENTRY: GlobalResourcesSentry
  APP_BASE_URL: string
  user: User | null
  MAX_FILE_SIZE: number
  DESCRIPTION_CHARACTERS_LIMIT: number
  EXPERIMENTAL: boolean
}
