export enum DOCUMENT_STATUS {
  CREATED = "CREATED",

  PARSING = "PARSING",
  PARSING_FAILED = "PARSING_FAILED",
  PARSING_SUCCESS = "PARSING_SUCCESS",

  CHUNKING = "CHUNKING",
  CHUNKING_FAILED = "CHUNKING_FAILED",

  EMBEDDING = "EMBEDDING",
  EMBEDDING_FAILED = "EMBEDDING_FAILED",

  SUCCESS = "SUCCESS",
}
