enum TOOL_INSTANCES_SOURCES {
  NONE = "NONE",
  FIGMA = "FIGMA",
}

export default TOOL_INSTANCES_SOURCES

export const TOOL_INSTANCES_LABELS: Record<TOOL_INSTANCES_SOURCES, string> = {
  [TOOL_INSTANCES_SOURCES.NONE]: "None",
  [TOOL_INSTANCES_SOURCES.FIGMA]: "Figma",
}
