enum USAGE_ALERT_TYPE {
  TRIAL_ENDING = "TRIAL_ENDING",
  TRIAL_ENDED = "TRIAL_ENDED",
  USAGE_LIMIT_ALMOST_REACHED = "USAGE_LIMIT_ALMOST_REACHED",
  USAGE_LIMIT_REACHED = "USAGE_LIMIT_REACHED"
}

export default USAGE_ALERT_TYPE

export const notClosableAlerts = [
  USAGE_ALERT_TYPE.USAGE_LIMIT_REACHED
]
