enum USER_ROLE {
  AUTHENTICATED = "AUTHENTICATED",
  STAFF_ACCOUNT = "STAFF_ACCOUNT",
  SELF = "SELF",
  CUSTOMER_ACCOUNT = "CUSTOMER_ACCOUNT",
  DEPARTMENT_ADMIN = "DEPARTMENT_ADMIN",
  DEPARTMENT_MEMBER = "DEPARTMENT_MEMBER"
}

export default USER_ROLE
