import { lstatSync, readdirSync, writeFileSync } from "fs"
import { join } from "path"

// ==================== GLOBAL ==================== //

const assetsPath = join(process.cwd(), "src/client")
const globalTypesPath = join(process.cwd(), "src/types")

const typeFilename = "assets.ts"
const typeName = "GlobalResources"

const ignoredFiles = [".DS_Store", ".gitkeep", ".keep"]

// ==================== HELPERS ==================== //

export function camelize(str: string[]) {
  return str
    .map((part, i) => {
      if (i > 0) {
        return part[0].toUpperCase() + part.slice(1)
      }

      return part
    })
    .join("")
}

function isIgnoredFile(nameOrPath: string) {
  const filename = nameOrPath.split("/").pop()!

  return ignoredFiles.some((name) => filename === name)
}

export function parseFilename(filename: string) {
  const split = filename.split(".")

  if (split.length > 2) {
    throw new Error(
      `Invalid filename: ${filename}\nFilenames should only have the format\`name-example.ext\``,
    )
  }

  const name = camelize(split[0].split("-"))
  const extension = split.length > 2 ? split.at(-1)! : split[1]
  const nameWithExtension = camelize([name, extension])

  return {
    extension,
    name,
    nameWithExtension,
  }
}

// ==================== FAVICON ==================== //

const faviconPath = join(assetsPath, "favicon")
const faviconSupportedExtensions = ["ico", "png", "webmanifest"]

const faviconFiles = readdirSync(faviconPath)
const faviconTypeNames: string[] = []

faviconFiles.forEach((filename) => {
  if (
    isIgnoredFile(filename) ||
    !faviconSupportedExtensions.some((ext) => filename.endsWith(`.${ext}`))
  ) {
    console.warn(
      `Ignoring file: ${join(faviconPath, filename)}\nPlease remove it from the directory`,
    )
    return
  }

  const stats = lstatSync(join(faviconPath, filename))

  if (stats.isDirectory()) {
    throw new Error(
      `Directories are not supported. Path: ${join(faviconPath, filename)}`,
    )
  }

  const name = filename.split("/").pop()!

  faviconTypeNames.push(name)
})

// ==================== FONTS ==================== //

const fontsPath = join(assetsPath, "fonts")
const fontsSupportedExtensions = ["otf", "ttf", "woff", "woff2", "svg"]

const fontsFiles = readdirSync(fontsPath)
const fontsTypeNames: string[] = []

fontsFiles.forEach((filename) => {
  if (
    isIgnoredFile(filename) ||
    !fontsSupportedExtensions.some((ext) => filename.endsWith(`.${ext}`))
  ) {
    console.warn(
      `Ignoring file: ${join(fontsPath, filename)}\nPlease remove it from the directory`,
    )
    return
  }

  const stats = lstatSync(join(fontsPath, filename))

  if (stats.isDirectory()) {
    throw new Error(
      `Directories are not supported. Path: ${join(fontsPath, filename)}`,
    )
  }

  const name = filename.split("/").pop()!

  fontsTypeNames.push(name)
})

// ==================== IMAGES ==================== //

const imagesPath = join(assetsPath, "images")
const imagesSupportedExtensions = ["gif", "jpeg", "jpg", "png", "svg", "webp"]

const imagesFiles = readdirSync(imagesPath)
const imagesTypeNames: string[] = []

imagesFiles.forEach((filename) => {
  if (
    isIgnoredFile(filename) ||
    !imagesSupportedExtensions.some((ext) => filename.endsWith(`.${ext}`))
  ) {
    console.warn(
      `Ignoring file: ${join(imagesPath, filename)}\nPlease remove it from the directory or add it to the supported extensions`,
    )
    return
  }

  const stats = lstatSync(join(imagesPath, filename))

  if (stats.isDirectory()) {
    return
  }

  const { name } = parseFilename(filename)

  imagesTypeNames.push(name)
})

// ==================== SCRIPTS ==================== //

// const scriptsPath = join(assetsPath, "scripts")

// ==================== STYLES ==================== //

// const stylesPath = join(assetsPath, "styles")

// ==================== TYPE ==================== //

const typeFileContent = `/*
  * This file was generated by scripts/assets_types.ts
  * Do not edit this file manually
  */

import { User } from "$services/UsersService"

export type ${typeName}Favicon = {
  ${faviconTypeNames.map((name) => `"${name}": string`).join("\n  ")}
}

export type ${typeName}Fonts = ${
  fontsTypeNames.length > 0
    ? `{
  ${fontsTypeNames.map((name) => `"${name}": string`).join("\n  ")}
}`
    : "Record<string, string>"
}

export type ${typeName}Images = ${
  imagesTypeNames.length > 0
    ? `{
  ${imagesTypeNames.map((name) => `"${name}": string`).join("\n  ")}
}`
    : "Record<string, string>"
}

export type ${typeName}Scripts = {
  main: string
}

export type ${typeName}Styles = string[]

export type ${typeName}Recaptcha = {
  RECAPTCHA_ACTIVE: boolean
  V2_SITE_KEY: string
  V3_SITE_KEY: string
}

export type ${typeName}Sentry = {
  SENTRY_DSN: string | null
  ENVIRONMENT: string
  SENTRY_VERSION: string | null
}

export type ${typeName} = {
  FAVICON: ${typeName}Favicon
  FONTS: ${typeName}Fonts
  IMAGES: ${typeName}Images
  SCRIPTS: ${typeName}Scripts
  STYLES: ${typeName}Styles
  RECAPTCHA: ${typeName}Recaptcha
  SENTRY: ${typeName}Sentry
  APP_BASE_URL: string
  user: User | null
  MAX_FILE_SIZE: number
  DESCRIPTION_CHARACTERS_LIMIT: number
  EXPERIMENTAL: boolean
}
`

writeFileSync(join(globalTypesPath, typeFilename), typeFileContent, {
  encoding: "utf-8",
})

console.log("Types generated successfully")
